### ISSUE TITLE
Internal Error Bug Report [Automatically Created via App]

### ISSUE THREAD

**Issue by Offside998** [xypwn/southpark-downloader-ui#10]
Version: 0.0.1 build 1
Error: GetEpisodeVTTSubtitles: get 'https://vs-tools.mtvnservices.com/caption/convert?mgid=mgid:file:gsp:alias:/mediabus/2020/05/05/03/20/32/9f8f57523adf4dedb9028159d6dd99bf/775037/raJzBNKwj3_HDSS0112X1_775037_5532626.dfxp.xml&accountName=intl.mtvi.com': HTTP error: 404 Not Found

**Comment by xypwn** [comment]
Thanks for the bug report. Is this still reproducible and how does it impair the app's functionality?

**Comment by xypwn** [comment]
Thanks for the bug report. What is your region and what episodes does this occur on?

**Comment by Offside998** [comment]
Thanks for the response. Region is Germany, and the error occurred on almost every epsisode after postprocessing.
I just tried downloading S03E01 (German) and the error occurred again.

**Comment by xypwn** [comment]
I'll look at it later today. Admittedly I haven't tested the app in a while, and I don't have much free time right now, but I'll see what I can do and let you know.

**Comment by xypwn** [comment]
I looked at the issue, and it seems Comedy Central reworked their whole video delivery system. I managed to reverse-engineer the changes, but it'll be a bit until I can fully integrate it them into the app. I still have to figure out a good way to remux audio and video into a single file, since they are now separate with the new changes. I'll post again when there's more progress.

**Comment by xypwn** [comment]
I implemented a downloader for their new system. The app should now work again after downloading the latest version. Feel free to open a new issue if you encounter any further problems.
