### ISSUE TITLE
Feature Request - Customizable Filename

### ISSUE THREAD

**Issue by Sk4lli** [xypwn/southpark-downloader-ui#2]
i would like to make a feature request for you or other which can code in GO, i can't.

Customizable Filenames where the User can change the naming with pre defined placeholders.

Examples (german):
South_Park_German_S01_E01_Best_Cartman_und_die_Analsonde.mp4
`title$_lang$_s$_e$_q$_episode$.ext$`

South_Park_S01E01.mp4
`title$_s$e$.ext$`

title§ = South_Park
s$ = Season Number
e$ = Episode Numbers 
q$ = Quality
lang$ = Language
episode$ = Episode name
ext$ = File Extension

**Comment by xypwn** [comment]
Hi, thanks for the issue. This is definitely a feature I have thought about implementing too. I would probably use a different syntax though. Firstly, I think the $ sign should be leading, second, I would rather use single letters. Also, I think the "title" and "ext" parameters are unnecessary since the former can just be normal text, and the latter should be immutable since it can only be mp4.

Maybe the GUI could look something like this:

---

File naming: `South_Park_$l_$s_$e_$q_$t`.mp4     `[Reset Button]`

Example: `South_Park_German_S01_E01_Best_Cartman_und_die_Analsonde.mp4`

Parameters:
- `$s`: Season Number
- `$e`: Episode Number
- `$l`: Episode Language
- `$t`: Episode Title
- `$q`: Episode Quality

You must include `$l`. Additionally, either both `$s` and `$e`, or just `$t` is required.

---

The GUI would include checking for a valid format/filename, and would check that `$l && (($s && $e) || $t)` exist.

**Comment by xypwn** [comment]
I just implemented it!

The feature is available in the newest release version.

![image](https://github.com/xypwn/southpark-downloader-ui/assets/54681180/d7def625-1b48-454d-a8c7-b8b2fcb10564)

Feel free to open another issue if you notice any problems with my implementation :)
