### ISSUE TITLE
Can't download some Episodes

### ISSUE THREAD

**Issue by MacClelland** [xypwn/southpark-downloader-ui#3]
Cant download some episodes. Maybe because there are no subs available.
Examples:
S1 E11
S2 E2
S2 E4
S7 E1
S7 E4
Language is german

I have seen you have fixed this issue, maybe you could rebuild the project with the fixes for Windows. Maybe that helps with downloading these episodes.

**Comment by xypwn** [comment]
Yup, I've fixed the issue in the source code, as mentioned in https://github.com/xypwn/southpark-de-downloader/issues/11#issuecomment-1705071128. Like I said, I don't have access to the SDKs needed to cross-compile all versions since I'm not home at the moment, but I should be able to upload the new binaries in a few hours :)

If you don't want to wait, you can compile it yourself. To do that, simply install [Golang](https://go.dev/dl/) and in the source code directory compile with the command `go build ./cmd/southpark-downloader-ui` (maybe it's `go.exe` on Windows, I never tried using Go on Win)

**Comment by MacClelland** [comment]
Installed GO1.21.0 and didnt Work
So I downloaded Go1.18.0 because in the go.mod file it states go1.18

Did that and got error:

# github.com/xypwn/southpark-downloader-ui/internal/gui
..\..\..\internal\gui\episodes.go:150:30: undefined: atomic.Int32
..\..\..\internal\gui\episodes.go:195:32: undefined: atomic.Int32

**Comment by xypwn** [comment]
1.21 should def work though, go is 100% backwards compatible

**Comment by MacClelland** [comment]
With 1.21 im getting this 

```
# runtime/cgo
gcc_libinit_windows.c: In function '_cgo_beginthread':
gcc_libinit_windows.c:143:13: error: implicit declaration of function '_beginthread'; did you mean '_cgo_beginthread'? [-Werror=implicit-function-declaration]
  143 |   thandle = _beginthread(func, 0, arg);
      |             ^~~~~~~~~~~~
      |             _cgo_beginthread
cc1: all warnings being treated as errors
```

**Comment by xypwn** [comment]
I just found this issue that mentions your exact error, seems to be pretty common with golang on Windows

https://github.com/golang/go/issues/59490#issuecomment-1581874198

**Comment by MacClelland** [comment]
Damn. that did the trick. compiled instantly.
And downloading these episodes works now. Thx for the help
